[toolchain]
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
token_manager = "6ggvxB6NumJAKqumAtpdGSb26hti8mZGTV6erWVZuAbC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./demo-parent-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
