[features]
seeds = false
skip-lint = false

[programs.devnet]
token_manager = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/_msharma/Documents/Projects/blockchain/solana/demo-smart-contract/demo-parent-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "BGC4wgx1o4oGkUFz5tqJAyLtnJr3M8iTZ3VXus6wMRWy"
program = "spl-token.so"