version: '3.8'

services:
  solana-dev:
    build: .
    container_name: demo-smart-contract-dev
    ports:
      - "8899:8899"  # Solana test validator
      - "8900:8900"  # Solana websocket
      - "9900:9900"  # Anchor localnet
    volumes:
      - .:/workspace
      - solana-ledger:/workspace/test-ledger
      - cargo-cache:/root/.cargo
      - solana-config:/root/.config/solana
    environment:
      - RUST_LOG=info
    stdin_open: true
    tty: true
    working_dir: /workspace

volumes:
  solana-ledger:
  cargo-cache:
  solana-config: